# -*- coding: utf-8 -*-
"""livellamenti_unito.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d36Lqzn_0xCIwJStMbEXv-7fS53oUCEY
"""

import streamlit as st
import pandas as pd
import numpy as np
from io import BytesIO

# --- 1. CONFIGURAZIONE PAGINA UNIFICATA ---
st.set_page_config(page_title="LIVELLAMENTI STOCK", page_icon="⚖️", layout="wide")

# --- 2. SIDEBAR: SCELTA MODALITÀ ---
st.sidebar.header("⚙️ Configurazione Analisi")
modalita = st.sidebar.radio(
    "Ambito dell'analisi:",
    ("Totale Rete", "Singolo Negozio (HUB)")
)

st.sidebar.divider()

# --- 3. PARAMETRI DINAMICI NELLA SIDEBAR ---
if modalita == "Singolo Negozio (HUB)":
    st.sidebar.subheader("Parametri Negozio HUB")
    codice_hub = st.sidebar.number_input(
        "Codice Negozio (Cedente)",
        min_value=0, max_value=9999, value=1562,
        help="Questo negozio sarà l'unico a cedere merce verso la sua stessa area."
    )
    soglia_max_cedente = st.sidebar.slider(
        "Soglia Max Avanzamento HUB",
        min_value=0.0, max_value=1.5, value=0.85, step=0.05
    )
else:
    st.sidebar.subheader("Parametri Rete")
    soglia_max_cedente = st.sidebar.slider(
        "Soglia Max Cedenti (chi ha troppo)",
        min_value=0.0, max_value=1.5, value=0.85, step=0.05
    )

# Parametri comuni
soglia_min_riceventi = st.sidebar.slider(
    "Soglia Min Riceventi (chi ha poco)",
    min_value=0.0, max_value=1.5, value=0.95, step=0.05
)

limite_minimo = st.sidebar.slider(
    "Limite minimo trasferimento (€)",
    min_value=0, max_value=2000, value=300, step=25
)

max_riceventi = st.sidebar.number_input("Num. Max Riceventi per gruppo", 1, 50, 10)

if modalita == "Totale Rete":
    max_cedenti = st.sidebar.number_input("Num. Max Cedenti per gruppo", 1, 20, 5)

# --- 4. TITOLO E DESCRIZIONE DINAMICA ---
if modalita == "Totale Rete":
    st.title("⚖️ LIVELLAMENTI PER ZONA (Totale Rete)")
    descrizione = "Ottimizzazione stock tra tutti i punti vendita della stessa area/reparto/apc."
else:
    st.title("🏢 LIVELLAMENTO SINGOLO NEGOZIO (HUB)")
    descrizione = f"Distribuzione stock in eccesso dal negozio {codice_hub} verso i riceventi della stessa area."

st.markdown(f"### {descrizione}")

# --- 5. SEZIONE REQUISITI FILE (TEMPLATE) ---
colonne_necessarie = ['Area Manager', 'Dept code', 'apc', 'Avanzamento', 'valore', 'ST Adj', 'Store code']

with st.expander("📂 REQUISITI DEL FILE EXCEL (TEMPLATE)"):
    st.write("Il file deve contenere esattamente queste colonne:")
    template_data = {
        "Area Manager": ["Mario Rossi"], "Store code": [1562], "Dept code": [123],
        "apc": ["A1"], "Avanzamento": [0.75], "ST Adj": [0.70], "valore": [-500.00]
    }
    st.table(pd.DataFrame(template_data))

    template_buffer = BytesIO()
    with pd.ExcelWriter(template_buffer, engine='openpyxl') as writer:
        pd.DataFrame(columns=colonne_necessarie).to_excel(writer, index=False)

    st.download_button("📥 Scarica Template Excel", template_buffer.getvalue(), "template.xlsx")

st.divider()

# --- 6. CARICAMENTO FILE ---
uploaded_file = st.file_uploader("Carica il file Excel", type=["xlsx"])

if uploaded_file is not None:
    df = pd.read_excel(uploaded_file, header=0)

    if not all(col in df.columns for col in colonne_necessarie):
        st.error(f"🚨 Colonne mancanti! Il file deve avere: {colonne_necessarie}")
        st.stop()

    log_trasferimenti = []
    testo_progresso = st.empty()
    barra_progresso = st.progress(0)

    # --- MODALITÀ: SINGOLO NEGOZIO (HUB) ---
    if modalita == "Singolo Negozio (HUB)":
        info_hub = df.loc[df['Store code'] == codice_hub, 'Area Manager'].unique()
        if len(info_hub) == 0:
            st.error(f"❌ Il negozio {codice_hub} non è presente nel file!")
            st.stop()

        area_manager_hub = info_hub[0]
        st.info(f"📍 Hub trovato! Area Manager: **{area_manager_hub}**")

        gruppi = list(df.groupby(['Dept code', 'apc']))
        for i, ((dept, apc), group) in enumerate(gruppi):
            testo_progresso.markdown(f"⏳ Analisi HUB: Reparto `{dept}` | Area **{area_manager_hub}**")
            barra_progresso.progress((i + 1) / len(gruppi))

            cedenti = group[(group['Store code'] == codice_hub) &
                            (group['valore'] < 0) &
                            (group['Avanzamento'] < soglia_max_cedente)].copy()

            riceventi = group[(group['Store code'] != codice_hub) &
                              (group['Area Manager'] == area_manager_hub) &
                              (group['Avanzamento'] > soglia_min_riceventi) &
                              (group['valore'] > 0)].sort_values(by='Avanzamento', ascending=False).head(max_riceventi).copy()

            if not cedenti.empty and not riceventi.empty:
                cedenti['disponibile_da_cedere'] = cedenti['valore'].abs()
                riceventi['capacita_ricezione'] = riceventi['valore']
                for idx_c, cedente in cedenti.iterrows():
                    q_da_dare = cedente['disponibile_da_cedere']
                    for idx_r, ricevente in riceventi.iterrows():
                        cap = riceventi.at[idx_r, 'capacita_ricezione']
                        if cap < limite_minimo: continue
                        trasferito = min(q_da_dare, cap)
                        if trasferito >= limite_minimo:
                            log_trasferimenti.append({
                                'Area Manager': area_manager_hub, 'Dept code': dept, 'apc': apc,
                                'Store Cedente': codice_hub, 'Avanzamento Cedente': round(cedente['Avanzamento'], 2),
                                'Store Ricevente': ricevente['Store code'], 'Avanzamento Ricevente': round(ricevente['Avanzamento'], 2),
                                'Valore Trasferito (€)': round(trasferito, 2)
                            })
                            q_da_dare -= trasferito
                            riceventi.at[idx_r, 'capacita_ricezione'] -= trasferito
                            if q_da_dare < limite_minimo: break

    # --- MODALITÀ: TOTALE RETE ---
    else:
        gruppi = list(df.groupby(['Area Manager', 'Dept code', 'apc']))
        for i, ((area, dept, apc), group) in enumerate(gruppi):
            testo_progresso.markdown(f"🔄 Area: **{area}** | Reparto: `{dept}`")
            barra_progresso.progress((i + 1) / len(gruppi))

            cedenti = group[(group['Avanzamento'] < soglia_max_cedente) & (group['valore'] < 0) & (group['ST Adj'] != 0)].sort_values(by='Avanzamento', ascending=True).head(max_cedenti).copy()
            riceventi = group[(group['Avanzamento'] > soglia_min_riceventi) & (group['valore'] > 0) & (group['ST Adj'] != 0)].sort_values(by='Avanzamento', ascending=False).head(max_riceventi).copy()

            if not cedenti.empty and not riceventi.empty:
                cedenti['disponibile_da_cedere'] = cedenti['valore'].abs()
                riceventi['capacita_ricezione'] = riceventi['valore']
                for idx_c, cedente in cedenti.iterrows():
                    q_da_dare = cedente['disponibile_da_cedere']
                    for idx_r, ricevente in riceventi.iterrows():
                        cap = riceventi.at[idx_r, 'capacita_ricezione']
                        if cap < limite_minimo: continue
                        trasferito = min(q_da_dare, cap)
                        if trasferito >= limite_minimo:
                            log_trasferimenti.append({
                                'Area Manager': area, 'Dept code': dept, 'apc': apc,
                                'Store Cedente': cedente['Store code'], 'Avanzamento Cedente': round(cedente['Avanzamento'], 2),
                                'Store Ricevente': ricevente['Store code'], 'Avanzamento Ricevente': round(ricevente['Avanzamento'], 2),
                                'Valore Trasferito (€)': round(trasferito, 2)
                            })
                            q_da_dare -= trasferito
                            riceventi.at[idx_r, 'capacita_ricezione'] -= trasferito
                            if q_da_dare < limite_minimo: break

    testo_progresso.empty()
    barra_progresso.empty()

    # --- 7. OUTPUT COMUNE ---
    if log_trasferimenti:
        df_output = pd.DataFrame(log_trasferimenti)
        st.success(f"✅ Analisi conclusa!")

        c1, c2 = st.columns(2)
        c1.metric("Trasferimenti", len(df_output))
        c2.metric("Valore Totale", f"{df_output['Valore Trasferito (€)'].sum():,.2f} €")

        st.subheader("📊 Riepilogo per Area Manager")
        riepilogo = df_output.groupby('Area Manager')['Valore Trasferito (€)'].agg(['sum', 'count']).rename(columns={'sum': 'Totale (€)', 'count': 'Operazioni'})
        st.table(riepilogo)

        st.subheader("📑 Dettaglio Piano")
        st.dataframe(df_output, use_container_width=True)

        output = BytesIO()
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            df_output.to_excel(writer, index=False)
        st.download_button("📥 Scarica Risultati", output.getvalue(), "piano_livellamento.xlsx")
    else:
        st.warning("⚠️ Nessun match trovato. Controlla i parametri e il file caricato.")