# -*- coding: utf-8 -*-
"""output_rizzato.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3_zI2ENb3zyMWpglc3ofPLat8sbSYPu
"""

import pandas as pd
import numpy as np

# 1. Carica il file assicurandoti che ID_PRELIEVO sia letto come TESTO
file_input = 'file.xlsx'
df = pd.read_excel(file_input, dtype={'ID_PRELIEVO': str})

# 2. Identifichiamo le righe dove l'emittente è diverso dal destinatario
# True se diversi, False se uguali
df['mismatch'] = df['ENTE_EMIT'] != df['ASSEGNZIONE']

# 3. Raggruppiamo per ID_PRELIEVO.
# 'transform(any)' controlla se esiste ALMENO un True (errore) in tutto il gruppo dell'ID.
# Se esiste un errore nell'ID, l'intera serie diventa True.
has_error_in_group = df.groupby('ID_PRELIEVO')['mismatch'].transform('any')

# 4. Creiamo la colonna CHECK: mettiamo 'x' solo se NON ci sono errori nel gruppo (~)
df['CHECK'] = np.where(~has_error_in_group, 'x', '')

# 5. Rimuoviamo la colonna tecnica e salviamo il file pulito
df_finale = df.drop(columns=['mismatch'])
df_finale.to_excel('Database_Pallet_Checked.xlsx', index=False)

print("File generato con successo!")