# -*- coding: utf-8 -*-
"""output_rizzato_STREAMLIT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V39NIelpWVpWwikjNrWpgIZS8XWQCoHL
"""

import streamlit as st
import pandas as pd
import numpy as np
from io import BytesIO

st.title("Verifica Corrispondenza Ente/Assegnazione")

# 1. Caricamento file tramite interfaccia Streamlit
uploaded_file = st.file_uploader("Carica il file Excel (file.xlsx)", type=["xlsx"])

if uploaded_file is not None:
    # 2. Lettura del file caricato
    # Usiamo uploaded_file al posto del nome del file fisso
    df = pd.read_excel(uploaded_file, dtype={'ID_PRELIEVO': str})

    st.info("Elaborazione in corso...")

    # --- IL TUO LOGICA DI CALCOLO ---
    # 3. Identifichiamo le righe dove l'emittente è diverso dal destinatario
    df['mismatch'] = df['ENTE_EMIT'] != df['ASSEGNZIONE']

    # 4. Raggruppiamo per ID_PRELIEVO
    has_error_in_group = df.groupby('ID_PRELIEVO')['mismatch'].transform('any')

    # 5. Creiamo la colonna CHECK
    df['CHECK'] = np.where(~has_error_in_group, 'x', '')

    # 6. Rimuoviamo la colonna tecnica
    df_finale = df.drop(columns=['mismatch'])

    # Visualizza un'anteprima nell'app
    st.write("Anteprima del risultato:", df_finale.head())

    # --- ESPORTAZIONE PER IL DOWNLOAD ---
    # Per permettere il download, dobbiamo salvare il file in un buffer di memoria (BytesIO)
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df_finale.to_excel(writer, index=False, sheet_name='Checked')

    processed_data = output.getvalue()

    # 7. Bottone per scaricare il file finale
    st.download_button(
        label="Scarica Database_Pallet_Checked.xlsx",
        data=processed_data,
        file_name='Database_Pallet_Checked.xlsx',
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    st.success("File elaborato con successo! Clicca sopra per scaricarlo.")

else:
    st.warning("Per favore, carica un file Excel per iniziare.")