[theme]
# Il colore primario per i pulsanti attivi, barre e accenti (Giallo Scuro/Oro)
primaryColor = "#D4AF37"

# Il colore di sfondo della pagina principale (Bianco)
backgroundColor = "#FFFFFF"

# Il colore della barra laterale (un grigio molto chiaro/azzurrato per fare contrasto col bianco)
secondaryBackgroundColor = "#F0F2F6"

# Il colore del testo principale (Blu Scuro, ottimo per la leggibilità sullo sfondo bianco)
textColor = "#0A192F"

# La font dell'app
font = "sans serif"
